id = "antigravity"
name = "Antigravity"
version = "0.0.1"
schema_version = 1
authors = ["Scott Lexium"]
description = "Brings Gemini support to Zed via Antigravity"
repository = "https://github.com/scott-lexium/antigravity"

[language_servers.antigravity]
name = "Antigravity Bridge Daemon"
language = "Markdown"
